name: CI

permissions:
  contents: read

on: [push]

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4', '8.5']
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - uses: actions/checkout@v6

    - name: Install dependencies
      run: composer install --no-interaction --no-progress

    - name: Run tests
      run: php vendor/bin/phpunit

    - name: Run phpstan
      run: php vendor/bin/phpstan

    - name: Run psalm
      run: php vendor/bin/psalm
